export const INIT_DONE = 'INIT_DONE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'

export const SET_ERROR = 'SET_ERROR'

export const SET_SELECTED_TAB = 'SET_SELECTED_TAB'
export const SET_ASSIGNED = 'SET_ASSIGNED'
export const SET_STATUS = 'SET_STATUS'

export const SET_TEMP_COMMENT = 'SET_TEMP_COMMENT'
export const ADD_TEMP_COMMENT = 'ADD_TEMP_COMMENT'
export const REMOVE_TEMP_COMMENT = 'REMOVE_TEMP_COMMENT'
export const SET_UNSAVED_TASKS = 'SET_UNSAVED_TASKS'

export const SELECT_TASK = 'SELECT_TASK'
export const SELECT_TASK_NEW = 'SELECT_TASK_NEW'
export const SET_TASK_SORT = 'SET_TASK_SORT'
