export const INIT_DONE = 'INIT_DONE'

export const TOKEN_AUTH = 'TOKEN_AUTH'
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const REMOVE_TASK = 'REMOVE_TASK'
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS'

export const SET_ERROR = 'SET_ERROR'

export const SET_SELECTED_TAB = 'SET_SELECTED_TAB'
export const SET_ASSIGNED = 'SET_ASSIGNED'
export const SET_STATUS = 'SET_STATUS'

export const SET_TEMP_COMMENT = 'SET_TEMP_COMMENT'
export const ADD_TEMP_COMMENT = 'ADD_TEMP_COMMENT'
export const REMOVE_TEMP_COMMENT = 'REMOVE_TEMP_COMMENT'
export const SET_UNSAVED_TASKS = 'SET_UNSAVED_TASKS'

export const LISTENER_START = 'LISTENER_START'
export const LISTENER_STOP = 'LISTENER_STOP'
export const UPDATE_FROM_LISTENER = 'UPDATE_FROM_LISTENER'

export const SELECT_TASK = 'SELECT_TASK'
export const SELECT_TASK_NEW = 'SELECT_TASK_NEW'
export const SET_TASK_SORT = 'SET_TASK_SORT'
